import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
from matplotlib.ticker import FuncFormatter

data1 = np.loadtxt('bruteForce.txt', comments='%')
data2 = np.loadtxt('modTestDiv.txt', comments='%')
data3 = np.loadtxt('bruteForceM.txt', comments='%')
data4 = np.loadtxt('Eratosthenes.txt', comments='%')
fig, ax = plt.subplots()
##plot rt vs n
ax.loglog(data1[:,0],data1[:,1],'ko')
ax.loglog(data1[:,0],data1[:,1],'k',label = 'bruteForce')
ax.loglog(data2[:,0],data2[:,1],'go')
ax.loglog(data2[:,0],data2[:,1],'g',label = 'modTestDiv')
ax.loglog(data3[:,0],data3[:,1],'bo')
ax.loglog(data3[:,0],data3[:,1],'b',label = 'bruteForceM')
#plt.legend(bbox_to_anchor=(1.05, 1.1), fancybox=True, shadow=True)
data_x = np.concatenate((data1[:,0],data2[:,0],data3[:,0]))
data_y = np.concatenate((data1[:,1],data2[:,0],data3[:,1]))
ax.axes.set_xlim([np.amin(data_x)*0.5,np.amax(data_x)*1.25])
ax.axes.set_ylim([np.amin(data_y)*0.1,np.amax(data_y)*1.25])
#ax.yaxis.set_minor_locator(MultipleLocator(5))
#ax.xaxis.set_minor_locator(MultipleLocator(5))
#plt.axis('equal')
ax.set_xlabel('N')
ax.set_ylabel('run-time (second)')
ax.legend(loc='upper left', frameon=False, shadow=False)
plt.savefig ('rt-vs-n.png')
plt.savefig ('rt-vs-n.jpg')
fig, ax = plt.subplots()
##plot rt vs n
ax.loglog(data1[:,0],data1[:,1],'ko')
ax.loglog(data1[:,0],data1[:,1],'k',label = 'bruteForce')
ax.loglog(data2[:,0],data2[:,1],'go')
ax.loglog(data2[:,0],data2[:,1],'g',label = 'modTestDiv')
ax.loglog(data3[:,0],data3[:,1],'bo')
ax.loglog(data3[:,0],data3[:,1],'b',label = 'bruteForceM')
ax.loglog(data4[:,0],data4[:,1],'o',color='#FF4F00')
ax.loglog(data4[:,0],data4[:,1],color='#FF4F00',label = 'Eratosthenes')
#plt.legend(bbox_to_anchor=(1.05, 1.1), fancybox=True, shadow=True)
data_x = np.concatenate((data1[:,0],data2[:,0],data3[:,0]))
data_y = np.concatenate((data1[:,1],data2[:,0],data3[:,1]))
ax.axes.set_xlim([np.amin(data_x)*0.5,np.amax(data_x)*1.25])
ax.axes.set_ylim([np.amin(data_y)*0.1,np.amax(data_y)*1.25])
#ax.yaxis.set_minor_locator(MultipleLocator(5))
#ax.xaxis.set_minor_locator(MultipleLocator(5))
#plt.axis('equal')
ax.set_xlabel('N')
ax.set_ylabel('run-time (second)')
ax.legend(loc='upper left', frameon=False, shadow=False)
plt.savefig ('rt-vs-n-eratos.png')
plt.savefig ('rt-vs-n-eratos.jpg')
plt.show()


